

	RLLABDIR = /home/aboudy/Documents/rllab

prepare: 
	rm -rf $(RLLABDIR)/debug
	rm -rf $(RLLABDIR)/cistar
	cp -r cistar $(RLLABDIR)

clean:
	rm -rf $(RLLABDIR)/debug
	find $(RLLABDIR) -name "*.xml" -type f -delete
