# Instructions:
# 1. Replace the path for RLLABDIR
# 2. Make a copy from Makefile.template to Makefile

RLLABDIR = <PATH TO RLLAB FOR CISTAR DIR>

prepare: 
	rm -rf $(RLLABDIR)/debug
	rm -rf $(RLLABDIR)/cistar
	cp -r cistar $(RLLABDIR)

clean:
	rm -rf $(RLLABDIR)/debug
	find $(RLLABDIR) -name "*.xml" -type f -delete
